nuxt/fonts

src/providers/google.ts

Just a very simple fix to sort the variables list for Google Fonts. This fixes #32.

fix(google): sort resolved variants when fetching font css

---

src/module.ts
src/providers/bunny.ts
src/providers/fontshare.ts
src/providers/google.ts
test/parse.test.ts

This pull request warns users when some of the font weights are not available, or throws an error when none of the font weights are available (as the latter situation causes a 400 error with an empty array).

feat: warn when font weights are not available

---

src/module.ts
src/providers/fontshare.ts
src/providers/google.ts
src/types.ts

This PR fixes #46. Just a simple fix which ensures `variants.weights` is composed of numbers.

 fix: normalize weights before passing to `resolveFontFaces`

---

README.md
playground/nuxt.config.ts
playground/pages/providers/adobe.vue
playground/pages/providers/adobe2.vue
src/css/parse.ts
src/module.ts
src/providers/adobe.ts
src/types.ts

This PR resolves #11. What is different from the proposal written in the issue is that when a font is matched in the kit, a regex filters out the `@font-face` declarations that are not related to the font requested.
I think the next thing we can work on this provider is to work with different kit IDs and treat them like separate providers.

feat: adobe fonts provider

---

src/css/parse.ts

Just a simple fix; this PR modifies `getFontDetails` so that it continues the loop instead of break if font family doesn't match because the input CSS might have font families other than the requested one. This fixes the "Could not produce font face declaration from adobe for font family Barlow Semi Condensed." error in the playground as I have multiple fonts in that kit.

fix: continue if font family doesn't match in `getFontDetails`

---

src/providers/local.ts

We are planning to move to [emitting absolute paths in `builder:watch` in Nuxt v4](https://github.com/nuxt/nuxt/issues/25339). You can see a little more about the history in the PR linked in that issue.
This PR is an attempt to use a forward/backward compatible approach, namely resolving the path to ensure it's absolute, then making it relative so your existing code will continue to work.
This should be safe to merge as is, but do let me know if you have any concerns about this approach.

fix: adopt forward-compatible approach to `builder:watch`

---

README.md

docs: mention non-latin subset support for adobe provider

---

README.md

As I understand, there are now more than four providers.

docs(readme): replace provider count

---

src/providers/adobe.ts

@danielroe 
This PR resolves #187. I'm not sure whether this `css_names` always have a single value, it's not documented anywhere.

fix(adobe): use provided `css_names` from API

---

docs/content/1.get-started/1.installation.md

There is no open issue as this pull request just fixes an incorrect link in the docs. 
The "open and issue" link on the installation page points to the Nuxt image repo instead of the Nuxt fonts repo. This PR fixes that.

docs: fix open an issue link on installation page

---

client/app.vue

improved devtools UI, using `NSplitPane` and `NSectionBlock` from `devtools-ui`

refactor(devtools): enhance UI with improvments

---

src/module.ts

resolves https://github.com/nuxt/fonts/issues/152

fix: add global `preload` links to entry chunk

---

playground/pages/providers/google.vue
src/plugins/transform.ts
test/parse.test.ts

@danielroe 
Resolves #291. `css-tree` does the parsing work automatically for us.

fix: scan font families declared in `font:`

---

src/assets.ts
src/module.ts

resolves https://github.com/nuxt/fonts/issues/341
resolves https://github.com/nuxt/fonts/issues/224
owing to how Nuxt attempts to handle public assets, it checks if a file _exists_ at the time of rendering the chunk.
in the first build of a site using Nuxt fonts, these files do not exist in the cache directory and so Nuxt will hard code these as `/_fonts/*`. subsequently they will exist and dynamic urls work (making reproductions harder).
this PR is a workaround, writing stub data at build-time to ensure the Nuxt handler picks up these urls as pointing to public files.

fix: write stub files in cache to trigger public asset handling

---

docs/content/1.get-started/4.providers.md

Resolves #397
I found myself struggling to understand what my local filenames were supposed to be called for the module to properly read them. Hopefully this small tweak makes it a tad more obvious how to structure the filenames.

docs: Add examples to local file lookup docs

---

docs/content/1.get-started/1.installation.md
docs/content/1.get-started/2.configuration.md

Ref https://github.com/nuxt/fonts/issues/209#issuecomment-2496066476
For a new user, it's not immediately obvious that only the 400 font weight is loaded for fonts. This PR aims to improve that by calling it out during the installation and troubleshooting steps.

docs: Callout limited default font-weights

---

scripts/update-changelog.ts

Resolves #401
The `bumpType` can be `null`. `newVersion` defaults it to `patch`, but the rendered message doesn't default it in the same way. This tweak makes sure that both default to `patch` in the same way.

chore: Fix bumpType default in changelog script

---

client/app.vue
src/devtools.ts

Resolves #400
When HMR runs, fonts are re-broadcasted even if they were already broadcasted prior; this results in fonts being shown in the DevTools continuously
---
- I'm not entirely sure what the data flow is between module and DevTools (this is my first foray into Nuxt module/devtools), so lemme know if this is a dirty hack rather than a workable fix
- I didn't see any tests for the devtools.ts file, so lemme know if that's somewhere I didn't spot! 🙂

fix: Don't broadcast font if it has already been loaded prior

---

docs/content/1.get-started/3.usage.md

TailwindCSS v4 had an update to the way you configure theme fonts variables.  The font family variable has been renamed from --font-family-* variables to --font-*  [See this pull request ](https://github.com/tailwindlabs/tailwindcss/pull/14885)
["resolves #409"](https://github.com/nuxt/fonts/issues/409)
- [ x] 📖 Documentation (updates to the documentation or readme)
To customize the font family this is how it now should be configured - 
Old way
```
@theme {
--font-family-display: "Inter", "sans-serif";
}
```
New way
```
@theme {
--font-display: "Inter", "sans-serif";
}
```

docs: update tailwind v4 example

---

client/app.vue
client/components/FontFileSize.vue

@danielroe 
Closes #460. Also includes some minor UI changes in order to fit the badge in.
Currently the file size is considered:
- *good* if <30KB; 
- *moderate* if <100KB; 
- *bad* if >100KB.

feat(devtools): display file size in devtools

---

docs/content/1.get-started/4.providers.md

There is no open issue, I hope that's okay for such a small doc change :innocent: 
This adds a clarification to the docs that the local provider does not simply load available font weights and styles. They have to be configured first.

docs: clarify that local provider does not load weights and styles as available automatically

---

src/assets.ts

resolves #565
When downloading a font file with a very long name, an `ENAMETOOLONG` error is thrown. This change fixes this by ensuring that the file name is kept in check.
Example URL From Google:
> https://fonts.gstatic.com/s/robotoflex/v27/NaN4epOXO_NexZs0b5QrzlOHb8wCikXpYqmZsWI-__OGbt8jZktqc2V3Zs0KvDLdBP8SBZtOs2IifRuUZQMsPJtUsR4DEK6cULNeUx9XgTnH37Ha_FIAp4Fm0PP1hw45DntW2x0wZGzhPmr1YNMYKYn9_1IQXGwJAiUJVUMdN5YUW4O8HtSoXjC1z3QSabshNFVe3e0O5j3ZjrZCu23Qd4G0EBysQNK-QKavMl12K4Uc5-TkjOSy.woff2

fix: hash cached font file name

---

docs/content/1.get-started/3.usage.md

Resolves #588
Adds a brief note to the UnoCSS usage section with the required config change to make if using the Wind4 preset. I've tried to follow Nuxt contributing and documentation guidelines, but this is my first PR to Nuxt, so please excuse any mistakes!

docs: add config for use with UnoCSS Wind4 preset

---

README.md

n/a
I find it more convienent having a section on the nuxt module / README that tells us how we can install the package so we don't have to click another link to find out how to install ithe module.
https://nuxt.com/modules/fonts
This is also consistent with other offical nuxt modules that have an Installation section in the README.
- https://nuxt.com/modules/seo#installation
- https://nuxt.com/modules/icon#setup-%EF%B8%8F
- https://nuxt.com/modules/i18n#install
- https://nuxt.com/modules/ui#installation

docs: add Installation section in README
